### ISSUE TITLE
Bug in check_samplesheet.py

### ISSUE THREAD

**Issue by evezeyl** [avantonder/bovisanalyzer#40]
### Description of the bug

Does not find headers for input file with many samples, even when it is correctly formated (created with your preparing script).

I then tested the validation script alone (this is not an issue with the rest of the pipeline).

-the error occurs in def sniff_format(handle): maybe because of def read_head(handle, num_lines=10):
`if not sniffer.has_header(peek):` does not work  - report a str error format with no attribute

I modified your script: 
commented:    lines 148-150 (as I was not sure how to fix that)

I also modified two other lines that were also reporting error str when dealing with handlers
177: modified from `with file_in.open(newline="") as in_handle:` to ` with open(file_in, newline='') as in_handle:`
195: modified from `with file_out.open(mode="w", newline="") as out_handle:` to `with open(file_out, mode="w", newline='') as out_handle:`

BovisAnalyzer runs successfully so far since this modification

Attached example of long input file

All the best
Eve

### Relevant files

[selection.csv](https://github.com/avantonder/bovisanalyzer/files/10966455/selection.csv)

**Comment by avantonder** [comment]
Dear Eve,

Apologies for the bug. This is one of the most annoying bugs I've had to deal with and occurs when the sample ids are of different lengths. I either got round this by making sure the sample ids were the same length or else made sure the `samplesheet.csv` file was ordered by the length of the sample ids.  Your issue finally got me to get round to finding a solution which I now have. I tested it on a subset for the samples you provided (downloading them first with fetchngs) and it no longer resulted in header error.  Hopefully, it's now fixed and I've created a new release (v1.2.2).

More generally, if you have any other feedback, I'd love to hear it.

Thanks,

Andries
