### ISSUE TITLE
TBPROFILER_PROFILE - often fails

### ISSUE THREAD

**Issue by evezeyl** [avantonder/bovisanalyzer#42]
### Description of the bug

I had troubles to make TBPROFILER_PROFILE work.
Sometimes with erratic error messages, like no passeword in the container, occasionally errors that seemed to indicate i/o process and others memory.
So I tried to make it run with a singularity container within the work directory for one sample to try to identify the problem. 

The paths for your assets parameters (external database) could not be open because it redirected to a path that was not available to the singularity container. It seems also that the path to the reads that are symlinked to the nextflow work directory was not accessible to the image. 
Once I binded the necessary paths to the containers, then it worked with the singularity image. So the problem is not there

Then I tried to make it work for a test sample in nextflow. I tried add binding paths to my nextflow working directory and to your assets. But I did not manage using the instructions : https://www.nextflow.io/docs/latest/config.html#config-singularity. I tried changing the runOptions  and engineOptions - for the specific process, and also in the singularity profile respectively but I am not so advanced at nextflow yet ... so that might be why. 
Then I found the following issue of one of my colleague 
https://github.com/nextflow-io/nextflow/discussions/2567
That had found a workaround. 

But I guess you do not want hard coding of image in the process... 
So I actually added SINGULARITY_BIND  to my bashrc, binding both the nextflow directory path And the path to your assets, this allowed the test run to work. (I had tried to bind directly your assets path with NF_ASSETS - but it lead to errors of not finding configurations ... so I reactivate).  

I am currently trying to complete the run on the full dataset. I see that some  TBPROFILER_PROFILE still fail, but less. I really boosted the memory parameters for this one so I am not sure it it still can be an issue. That appeared at least then to be an easy fix for me. 

 I am assuming that it might just be that some isolates are of too poor quality or eitherwise sequenced too deep : some have an expected coverage of ca 800 (I did not filter anything before setting in). 
You have quality checks and downsampling, do you use that before to sending to TBPROFILER_PROFILE (did not manage to poke around yet to discover that) .

I also modified the configuration so it does not bug so often - so instead of terminate to ignore, and added a retry step, because it was too erratic with different process bugging here and there, so I needed a way to see those that all fail consistently to be able to adjust memory parameters and try to see where really processes were failing. 

Coming back to you if I discover more.

All the best
Eve 

### System information

HPC (centosOS I think) , slium exectutor ,singularity container, version  (pulled your modification for the sample file directly (should correspond to your last commit on main)

**Comment by avantonder** [comment]
Hi Eve,

By the sounds of it there are at least three types different errors being generated:

1) tb-profiler fails for no obvious reason. This unfortunately does happen and, in nearly all cases this appears pretty random, being resolved at the next attempt. I've processed thousands of samples in multiple runs of the pipeline and never had them complete without a handful of tb-profiler failures. A tiny number of samples have failed to work eventually. I'm not entirely sure why tb-profiler fails as during testing I wasn't able to get the same samples to fail more than once or twice.
2) Insufficient memory for the jobs to run. This is possible. tb-profiler currently asks for 16Gb of memory which may be insufficient for edge cases. That being said, tb-profiler is run post sub-sampling so the expected read coverage should be =< 100X. If asking for more memory meant fewer failures, I can change the pipeline so tb-profiler asks for more. You can check the results of trimming, subsampling and removing duplicate reads in the `read_stats_summary.tsv` file in the `results/metadata` directory. If the pipeline didn't get as far as creating the summary file, the individual sample results are in the `results/read_stats` directory. To check the amount of memory being used by each process, have a look at the files in the `results/pipeline_info` directory.
3) Issues with singularity asking for a username. This seems to happen with some installs of singularity. Some of the jobs just fail whilst others run using the same singularity container. I've not been able to find a satisfactory fix to this.

Hope this helps,

Andries
