### ISSUE TITLE
Pseudogenome file

### ISSUE THREAD

**Issue by jloubser** [avantonder/bovisanalyzer#43]
### Description of feature

Good day,

Apologies if I'm at the wrong place here...
I tried joining the Slack channel but can't seem to find it.

Am I correct in assuming that the pseudogenome alignment can be used directly as an input for iqtree for example to generate a phylogenetic tree? Or does it need further processing/filtering?

Thank you!
Really enjoying this pipeline!

**Comment by jloubser** [comment]
Or rather the snp-sites extracted from the pseudo-alignment, sorry.

**Comment by avantonder** [comment]
Hi,

Thanks for getting in touch. Yes, the two files in the snpsites directory can be fed directly to iqtree. This is my usual go to command (you may need to adjust memory/threads for your system):

`iqtree -fconst $(cat constant_sites.txt) -s filtered_alignment.fas -nt AUTO -ntmax 8 -mem 8G -bb 1000 -m MFP`

Kind regards,

Andries
